### ISSUE TITLE
3Bot server killed by OOM [development_memoryleak]

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_threebot#400]
This morning I discovered the 3bot server of the production explorer was stopped.

After investigation I found this:

![2020-03-10_2191x242_scrot](https://user-images.githubusercontent.com/303164/76287886-cb68f280-62a5-11ea-9df8-f205d819c7e1.png)

Seems there is another memory leak...

**Comment by waleedhammam** [comment]
We found that logs count in redis for threebotserver is > 8k, there was a bug in logs cleaning, fixed by: https://github.com/threefoldtech/jumpscaleX_core/pull/598/files

- To verify, added a monitoring script to get more info in case a crash happend
![Screenshot from 2020-03-11 13-19-39](https://user-images.githubusercontent.com/10658229/76412248-f897cc80-639b-11ea-8474-4932ade8c42c.png)

- Things now seems to be stable, leaving for tonight for more checks
![Screenshot from 2020-03-11 13-18-37](https://user-images.githubusercontent.com/10658229/76412346-1e24d600-639c-11ea-9550-987167f8db4b.png)

Thanks @grimpy

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_core/pull/610

this PR decreases the memory leak but does not fix the leak itself

**Comment by zaibon** [comment]
We've did more investigation today. It seems the biggest leaks come from the workload_manager actor.
But we failed to identify exactly why or what is leaking
